name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target: [ubuntu-24.04, ubuntu-24.04-arm]
    
    runs-on: ${{ matrix.target }}

    steps:
    - uses: actions/checkout@v4
    - name: WiredTiger submodule init
      run: git submodule update --init --recursive
    - name: Build
      run: cargo build --workspace
    - name: Run tests
      run: cargo test --workspace
    - name: Clippy
      run: cargo clippy -- -D warnings
